version: '1.0.0'
services:
  youtube-downloader:
    build:
      context: .          # 使用当前目录作为构建上下文
      dockerfile: Dockerfile  # 指定Dockerfile文件的名称
    ports:
      - "5000:5000"      # 将容器的5000端口映射到主机的5000端口
    volumes:
      - .:/app            # 将当前目录挂载到容器的/app目录，用于在容器内同步代码更改